#!/bin/sh
# install AUR packages with cower
# taken and modified from http://jasonwryan.com/blog/2013/04/09/helpers/
# "$_" - last argument of last function call

mkdir -p "$HOME/local/aur"
cd "$_" && cower -d "$1"
builddir="$_"
cd "$builddir" && ec PKGBUILD

makepkg -si && cd - &>/dev/null

read -p "Remove Build directory? [Y/n]? " yn
if [ "$yn" = "y" ]; then
    printf "\n%s\n" "Removing build directory..."
    rm -rf "$builddir"
else
    printf "%s\n" "Build completed."
fi